/**
 * アクションタイプまとめ
 * @type {{AUTH: string; AUTH_START: string; AUTH_SUCCESS: string; AUTH_FAIL: string; AUTH_LOGOUT: string; AUTH_SIGN_UP: string; AUTH_END: string; FRIEND_SHOW: string; FRIEND_LIST: string; FRIEND_SUCCESS: string; FRIEND_FAIL: string; FRIEND_START: string; FRIEND_CAHT_LIST: string; FRIEND_ADD_CHAT: string; FRIEND_FRESH: string}}
 */
const ActionTypes = {
    AUTH: 'AUTH',
    AUTH_START: 'AUTH_START',
    AUTH_SUCCESS: 'AUTH_SUCCESS',
    AUTH_FAIL: 'AUTH_FAIL',
    AUTH_LOGOUT: 'AUTH_LOGOUT',
    AUTH_SIGN_UP: 'AUTH_SIGN_UP',
    AUTH_END: 'AUTH_END',
    FRIEND_SHOW: 'FRIEND_SHOW',
    FRIEND_LIST: 'FRIEND_LIST',
    FRIEND_SUCCESS: 'FRIEND_SUCCESS',
    FRIEND_FAIL: 'FRIEND_FAIL',
    FRIEND_START: 'FRIEND_START',
    FRIEND_CAHT_LIST: 'FRIEND_CAHT_LIST',
    FRIEND_ADD_CHAT: 'FRIEND_ADD_CHAT',
    FRIEND_FRESH: 'FRIEND_FRESH',
    AUTH_CHECK_START: 'AUTH_CHECK_START'
};

export default ActionTypes;